baseURL: https://dev.forakey.com/
languageCode: en-us
title: For a Key
theme: "hugo-scroll"

disableKinds: ["section", "taxonomy", "term", "RSS"]
enableRobotsTXT: true
# googleAnalytics: UA-199311806-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  copyright: "© forakey"
  title: For a Key
  description: "Make life more easier"
  favicon: "images/favicon.png"  
  images: ["images/cover-image.jpg"]
  # keywords: [Blog, Portfolio, fharsanto]
  DateFormat: "2 January, 2006"
  defaultTheme: auto # dark, light
  hidedesignbyline: true

  outputs:
    home:
      - HTML
      - RSS
      - JSON    